server.port: 8081
spring.web.resources.static-locations: file:src/main/resources/static
spring.datasource:
  url: jdbc:h2:mem:db1
  driverClassName: org.h2.Driver
  username: sa
  password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create-drop
spring.h2.console.enabled: true
logging.level.root: info