server.port: 8081
spring.datasource:
#  url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS S0\;SET SCHEMA S0;
  url: jdbc:h2:~/.h2/testdb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;SCHEMA=PUBLIC
  driverClassName: org.h2.Driver
  username: sa
  password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create-drop

spring.h2.console.enabled: true

logging.level.root: info
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source: metadata
